### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by gerroon** [jensstein/oandbackup#105]
Compression.getfiles: listfiles returned null

then crashes. It crashes with bunch of them But in this particular case it crashed when backing up AIMP (apk+data)

**Comment by jensstein** [comment]
thanks for the report.
which android version do you use?
please try this apk: https://drive.google.com/file/d/0B0bNUNWd2wPPRzA3VjZ6WVUyMzQ/view?usp=sharing - it just adds a permission to read external storage, which may be the problem.
if it still crashes please send me a logcat made with that apk.

**Comment by gerroon** [comment]
I am on 4.4.4 CM

**Comment by gerroon** [comment]
That seems to fix it.

**Comment by jensstein** [comment]
cool :)
