### ISSUE TITLE
Back up home screen shortcuts with app

### ISSUE THREAD

**Issue by mvglasow** [jensstein/oandbackup#112]
Thanks for a great and highly useful app! There is one extra that I'm missing, though: uninstalling an app on Android will also delete its home screen shortcut, and restoring the app won't bring it back. Is there any way to back up and restore shortcuts together with the app?

**Comment by jensstein** [comment]
no, i'm afraid not. at least not to my knowledge. shortcuts are specific to the launcher so backing up and restoring them individually would require knowing how they are stored by any launcher out there.
with the trebuchet launcher they are stored in the file launcher.db. so backing up and restoring all shortcuts in the same operation can be done.

one could of course just create a new shortcut with the com.android.launcher.action.INSTALL_SHORTCUT intent action. but as far as i know, you cannot control the placement of shortcuts created like this so i don't think that would be a good solution (it would also require requesting a new permission).

but if you have any ideas for doing this, i would like to hear them :)

**Comment by ildar** [comment]
I've seen the CM 12.1 trebuchet remembers shortcuts between installations.
Also IMHO there're very few cases when one wants to uninstall an app then
install it back. If you want to reset app's data, one can do it without
uninstalling

**Comment by mvglasow** [comment]
My use case is switching between APKs with different signatures (e.g. F-Droid vs. my own build) and preserving data.

Just to clarify: so shortcuts on the home screen (not the app drawer) are managed by the launcher?

Restoring via the intent action is certainly better than nothing, even if placement is somewhat random. Is there a way to query which shortcuts are currently present, and what they point to? If so, then backup could examine existing shortcuts and set a flag, then recreate them on restore.

I'm on CM 12.1 but shortcuts on the home screen are not preserved. Do I need to enable that somewhere?

**Comment by ildar** [comment]
The home screen is a launcher by definition. Android allows a user to
switch launchers.
Shortcuts belong to a launcher (actually if you have a couple of launchers,
they can have their own set of shortcuts, widgets etc.)
Bottomline:
1. You'd better discuss that with launcher guys. Whichever launcher you
like.
2. You are hardly to find a decision that works with all launchers.

**Comment by jensstein** [comment]
yes, as ildar said, the home screens are completely handled by the active launcher.
it's only possible to get the current shortcuts by examining the storage of that particular launcher. so in pratice it's not possible because we could only support a very limited set of all the available launchers and the functionality could break every time on of them had an update.
check this answer from dianne hackborn: https://stackoverflow.com/questions/6196776/android-get-installed-shortcuts

**Comment by mvglasow** [comment]
Pity, I'd hoped that there'd be some API mechanism to query existing shortcuts, but it seems this is another place in which Android's design is... well... sub-mediocre. I agree, though, that launcher-specific hacks are a bad thing, especially when we're talking about undocumented features or prying under the hood.

**Comment by jensstein** [comment]
yes, it is a pity that it's not possible through the api. this particular feature would be too unwieldy to manage through hacks.
you could consider asking the developers of the launcher you use for a similar feature. [ACTION_PACKAGE_ADDED](https://developer.android.com/reference/android/content/Intent.html#ACTION_PACKAGE_ADDED) is broadcast when applications are installed, so a launcher could listen for that and set a new shortcut if needed.

**Comment by DJaeger** [comment]
Two possible sollutions could be:
1. Restore Data of the launcher after restoring the app, as it should have the location of the shortcut in its data backup.
2.Calling the intent to create a shortcut, as stated before, but that would create the short anywhere.
It could be, that some launchers are preserve the shortcut location even after uninstalling and will restore the location.
The Google Play Store is also creating a shortcut after installing an app, maybe also by calling the intent.
