### ISSUE TITLE
Restoring Signal / LibreSignal

### ISSUE THREAD

**Issue by SecUpwN** [jensstein/oandbackup#115]
Good evening Ladies and Gentlemen!

@jensstein recommended that I open this fresh Issue to publicly track our progress restoring messages from `Signal` (I am using the GCM-free version with websocket support called [LibreSignal](http://www.kuketz-blog.de/android-signal-ohne-google-cloud-messaging/)) and currently face the Issue that I need to restore it from a nandroid backup **after moving from Android 5 to Android 6**. Of course `TitaniumBackup` can restore nandroid backups, but I am not sure if it does that correctly since after restoring the app and data from the nandroid backup, I am prompted with the fresh registration screen as if I've never used the app. Uncool, I would lose tons of important messages! Solving this Issue is also important for `oandbackup` to know how to correctly implement feature #114.

This is what has already been tested with the great help of @jensstein:

* Backed up fesh APK of `LibreSignal` using `oandbackup`
* Extracted `data/org.thoughtcrime.securesms` from `TWRP` backup named `data.ext4.win000`
* Used a special version of `oandbackup` to convert the extracted `org.thoughtcrime.securesms`
* Did a normal restore of APK and data using the special version of `oandbackup`

Current result: I can open `LibreSignal`, yet again I am prompted with a fresh registration screen.
What did I miss? How to find out which things have not been correctly restored?

**Comment by jensstein** [comment]
also, this might be related to a transition between android 5 and 6, right?

since i cannot reproduce this myself, could you please run the command "ls -lRZ" on the libresignal data directory (maybe /data/data/org.thoughtcrime.securesms)? i need the output from this command both when the data has been restored with oandbackup and with data generated with libresignal after the restored data has been cleaned. the point is that i need to see if there are any significant differences to ownership, permissions or security contexts between the restored data and the data as it is produced by libresignal.

**Comment by SecUpwN** [comment]
>also, this might be related to a transition between android 5 and 6, right?

Whoa, thanks for reminding me, totally forgot that. OP has been updated.

>i need the output from this command both when the data has been restored with oandbackup and with data generated with libresignal after the restored data has been cleaned.

May I copy the directories that need the check over to my Linux system, or will that change the ownership, permissions and security contexts? Option `-Z` of `ls` seems not avlaible on Android.

**Comment by jensstein** [comment]
it needs to be run on android so we can be sure everything is unchanged (i know you can preserve these things with rsync for example but it's best to run it on the original files).
if your ls doesn't have -Z then you probably need to find a busybox version where it does. it's the flag that tells ls to show security contexts so it's pretty important on android 6.
here is an armv7 version of busybox i compiled myself which includes the flag: https://drive.google.com/file/d/0B0bNUNWd2wPPLVhMVjZLTlpXUnc/view?usp=sharing

**Comment by SecUpwN** [comment]
>here is an armv7 version of busybox i compiled myself which includes the flag

Thanks, I moved your file to `/system/xbin/`, set the same permissions for it like all the other binaries and rebooted, but my Terminal Emulator still tells me that `-Z`would be an invalid option. What did I do wrong?

**Comment by jensstein** [comment]
(you didn't need to reboot)
try running it with the absolute path to busybox: ```/system/xbin/busybox ls -lRZ```

**Comment by SecUpwN** [comment]
>try running it with the absolute path to busybox

Did so, same thing. In fact, I had `Busybox Pro 32` on my phone, wich I just uninstalled due to it crashing constantly. But it seems as if it successfuly previously installed `BusyBox v1.24.1` into `/system/xbin/`. I then checked the `PATH` with `which busybox` and noticed that my Terminal Emulator used its own `busybox` and even its own version of `ls`. The simplest solution to all these Issues was to make my the Terminal Emulator request `ROOT` access by typing `su`, and then use the commands you previously said. Bottom line: **Get ROOT access when your phone is rooted!** ;-) Below are the results, hope they help.

* From the extracted `data.ext4.win000` TWRP file:

```
/storage/emulated/0/recoverme/data.ext4.win000/data/data/org.thoughtcrime.securesms:
-rw-rw---- root     sdcard_rw          u:object_r:fuse:s0 lib
```

>...and with data generated with libresignal after the restored data has been cleaned

What do you mean by that? Which files do I need to touch and how?

**Comment by jensstein** [comment]
well, if this is what's in your backup then i think i know your problem because there doesn't seem to be any data at all there. maybe you should try to find out if any of it's data is in the external storage (usually something like /sdcard/Android/data).

but just for good measure, you need to run this exactly as typed: ```/system/xbin/busybox ls -lRZ /data/data/org.thoughtcrime.securesms``` from a terminal with superuser privileges. we can't use the information from the twrp backup for anything.
the part about cleaned data means that you have to go into the android settings under apps and choose to delete the data of the program (data löschen in german i think). then you need to use the program to send some messages and make some calls or whatever you use the program for. and then you need to run ```ls``` again.

**Comment by SecUpwN** [comment]
>well, if this is what's in your backup then i think i know your problem because there doesn't seem to be any data at all there. maybe you should try to find out if any of it's data is in the external storage (usually something like /sdcard/Android/data).

Maybe the data is located in another subfolder like `/data.ext4.win000/data/app`? Here is the result:

```
$ su
$ /system/xbin/ls -lRZ /storage/emulated/0/recoverme/data.ext4.win000/data/app/org.thoughtcrime.securesms-2
total 16
-rw-rw---- 1 root sdcard_rw u:object_r:fuse:s0    0 2016-01-07 23:55 base.apk
drwxrwx--x 3 root sdcard_rw u:object_r:fuse:s0 4096 2016-01-07 23:55 lib
drwxrwx--x 3 root sdcard_rw u:object_r:fuse:s0 4096 2016-01-07 23:55 oat

/storage/emulated/0/recoverme/data.ext4.win000/data/app/org.thoughtcrime.securesms-2/lib:
total 8
drwxrwx--x 2 root sdcard_rw u:object_r:fuse:s0 4096 2016-01-07 23:55 arm

/storage/emulated/0/recoverme/data.ext4.win000/data/app/org.thoughtcrime.securesms-2/lib/arm:
total 0
-rw-rw---- 1 root sdcard_rw u:object_r:fuse:s0 0 2016-01-07 23:55 libcurve25519.so
-rw-rw---- 1 root sdcard_rw u:object_r:fuse:s0 0 2016-01-07 23:55 libredphone-audio.so

/storage/emulated/0/recoverme/data.ext4.win000/data/app/org.thoughtcrime.securesms-2/oat:
total 8
drwxrwx--x 2 root sdcard_rw u:object_r:fuse:s0 4096 2016-01-07 23:55 arm

/storage/emulated/0/recoverme/data.ext4.win000/data/app/org.thoughtcrime.securesms-2/oat/arm:
total 0
-rw-rw---- 1 root sdcard_rw u:object_r:fuse:s0 0 2016-01-07 23:55 base.odex
```

**Comment by jensstein** [comment]
it's not in /data/app - that's apks and their files.
you could try running something like ```find $twrpbackup -name \*securesms\*``` on your extracted twrp backups to see if you can find the data. maybe try extracting all the archives, not just data.ext4.win000.
if you still can't find the data you could try restoring your whole system from the twrp backup and make a backup of signal with the restored data with oandbackup. then you can verify that the data is in fact backed up before you return to android 6.

**Comment by SecUpwN** [comment]
>you could try running something like find $twrpbackup -name \*securesms\* on your extracted twrp backups to see if you can find the data. maybe try extracting all the archives, not just data.ext4.win000.

I've done that. Please help me to find out if there is something useful in [this logfile](https://defuse.ca/b/hlM30CI4). Thank you.

**Comment by jensstein** [comment]
there doesn't seem to be anything there. try restoring the twrp backup.

**Comment by SecUpwN** [comment]
>there doesn't seem to be anything there. try restoring the twrp backup.

And that's the catch: Restoring it results in the same thing: When opening `LibreSignal`, I am being prompted with the registration screen. Not sure if that means the data has just wrong permissions or if the data is really gone. I guess I have no other choice but to restore my superold plaintext backup then? :(

**Comment by jensstein** [comment]
the data doesn't seem to be in your backup then. it's probably not just wrong permissions.
i don't know what your plaintext backup is, but yes, try restoring from that.

**Comment by SecUpwN** [comment]
>i don't know what your plaintext backup is, but yes, try restoring from that.

It is just the plaintext of all SMS saved as `*.xml` which I can import back into `LibreSignal`. But that would mean I will lose a huge bunch of important SMS. Learning the hard way right now to do at least one nandroid every week and definitely when upgrading the Android system. Does it make sense to restore the old nandroid (which is bootlooping) and then trying to get hold onto the restored data of `LibreSignal` by mounting the SD via `TWRP`, then do the file analysis like above again?

**Comment by jensstein** [comment]
twrp generates a file called recovery.log which tracks every file that it backs up (it seems - and maybe log generation is an option, i can't remember). try running ```grep org.thoughtcrime.securesms``` on that file to see what was backed up from signal. you should have lines looking like "I:addFile '/data/data/some.app.here' including root: 0"
i don't think you would find anything that you can't find by extracting the twrp backup files but you could try restoring your nandroid and then using ```adb shell``` while in your recovery to for example run the find command.

also, if you do import your xml file, i would be very interested if you could try backing up that data with oandbackup and verifying that it is actually backed up.

**Comment by SecUpwN** [comment]
>also, if you do import your xml file, i would be very interested if you could try backing up that data with oandbackup and verifying that it is actually backed up.

When it boils down down to this, which version shall I use? The current release, or your special version?

**Comment by jensstein** [comment]
use this one from issue 111: https://drive.google.com/file/d/0B0bNUNWd2wPPMUVmMmFTZ2pRcGM/view?usp=sharing

**Comment by SecUpwN** [comment]
I have managed to boot back into Android 5 where the phone app crashes every few seconds but was able to launch `LibreSignal` after more than 10 minutes clicking `OK` on each crash notification. I guess when I made the nandroid, the data of `LibreSignal` was already gone, otherwise it would show up. Shit!

To thank you for your awesome help with this Issue, I've restored my remaining plaintext into the freshly set up `LibreSignal` on Android 6, backed everything up with `oadnbackup` and deleted the whole app. 
Result of restoring via `oandbackup`: **Works like a charme, everything is there: Data, SMS and no nagging registration screen as if I've never used the app!** I will now primarily use `oandbackup` and fully ditch `TitaniumBackup` once you release the latest version to F-Droid. Monitoring #114 now. ;-)

**Comment by jensstein** [comment]
i'm sorry to hear you've lost your data then.
but good that oab works at least.
the new release could be in the beginning of next week (and then some time before fdroid gets it built and distributed) :)

**Comment by piratenpanda** [comment]
Did someone test with the "real" Signal? When restoring with TiBu I have to unregister and register again to receive push notifications again. Does Oandbackup work better at this?

**Comment by SecUpwN** [comment]
>Does Oandbackup work better at this?

I can confirm that the latest `oandbackup` works perfectly. Completely replaced `TitaniumBackup`.
