### ISSUE TITLE
Website for oandbackup

### ISSUE THREAD

**Issue by lightonflux** [jensstein/oandbackup#118]
oandbackup is a helpful app, but it is not really easy to discover. You need to be adventurous and test all the apps in fdroid or rely on recommendations by other people. It is not in gplay and there is no website. Okay there is the readme on github, but we all know that nobody™ reads READMEs. 

So a website. 

My suggestion is that we host it on [github.io](https://pages.github.com/) and use [jekyll](http://jekyllrb.com/docs/quickstart/) with a FOSS (single page) theme to reduce the work we have to do. And to keep everything simple and in one repo. 

I would be happy work on the website and its content, as long as someone volunteers for proof reading. 

One example single page theme is [SinglePaged](https://github.com/t413/SinglePaged) ([Production example](https://jangernert.github.io/feedreader/))

The only thing i need from @jensstein is a fresh repo for the site and some consent regarding the theming. I would like something colourful.  But it doesn't have to be single paged. If you would like to have a small blog for release announcements i would do that as well.   
### Theme suggestions:

[Jekyll themes index site](http://jekyllthemes.org/)
- [SinlePaged](http://jekyllthemes.org/themes/singlepaged/) MIT - colourful and single paged
- [ Linear](http://jekyllthemes.org/themes/linear/) CC
- [DopeTrope](http://jekyllthemes.org/themes/dopetrope/) CC
- [Materialize](http://jekyllthemes.org/themes/materialize/) MIT - quite boring
- [Sleek blog](http://jekyllthemes.org/themes/sleek_blog/) MIT - quite bloggy and flashy
- [dotX](http://jekyllthemes.org/themes/dotx/) MIT - very minimal
- [mug](http://jekyllthemes.org/themes/mug/) MIT - hides menu by default
- [lora](http://jekyllthemes.org/themes/lora/) MIT - simple and very classic layout
- [nandomoreira.me](http://jekyllthemes.org/themes/nandomoreira.me/) MIT 
- [modern blog](http://jekyllthemes.org/themes/modernblog/) GPL - it like a presentation for the html demo scene LOOK AT IT's DEMO!
- [creative theme](http://jekyllthemes.org/themes/creative-theme/) Apache2 - very startup-y
- [read only](http://jekyllthemes.org/themes/read-only/) CC
- [ion](http://jekyllthemes.org/themes/ion/) CC
- [horizons](http://jekyllthemes.org/themes/horizons/) CC
### Content for the website:
- screenshots
- feature listing
- getting involved section (for code, issues and so on)
- Download section (with fdroid badge) 
- changelog history (kind of) [example](https://jangernert.github.io/feedreader/)
- (optional) blog section for release announcements and tutorials, …

**Comment by DJaeger** [comment]
Great idea.
I will sponsor and have already registered and configured the domain [oandbackup.org](http://oandbackup.org).

After creating the [Github Page] (https://pages.github.com/) you have to do the following to get the domain working:
* In the "Branches" menu, switch to the "gh-pages" branch.
* Above the file list, click New file.
* In the file name field, type CNAME (with all caps!).
* In the new file, add a single line with only ```oandbackup.org``` as content.
* At the bottom of the page, type a short, meaningful commit message that describes the change you made to the file.
* Below the commit message fields, choose to add your commit to the current branch.
* Click Propose new file.

**Comment by jensstein** [comment]
this is a brilliant idea :) if you want to do the content, i will be happy to proof-read.

in regards to the design of the page the only requirement i would have is that it has to work without javascript - javascript is okay but it cannot be the exclusive provider of some functionality on the page.
a single-page design is fine as long as it doesn't have any fancy transitions or animations. and colourful is absolutely good.
also, i think it's kind of important that we make some meaningful changes to the theme so that we don't end up with a page identical to one somebody else is using.

i don't know about a blog - there usually isn't that much to tell about a release that isn't already in the changelog. but i would be happy to be convinced otherwise too.
one thing we could have that isn't on your list could be pointers to downloading non-release builds in the download section.

would you be able to make a couple of mockups from some of the themes @lightonflux ? for example based on SinglePaged, Ion and/or Linear.

and thanks a lot for the domain donation, @DJaeger :) i will set up the github side of it when we have some content.

**Comment by lightonflux** [comment]
I thinkg i continue with ion. It works well without js (well all three do). And has a very classical layout. Linear on the other hand has a background image, which look nice but is hard to populate. We are not osmand and can use a map as background.

Sadly many of the themes including ion use js for responsiveness. Is that okay. I know how to archive some degree of responsiveness via CSS only (if the browser is new enough) but not to the level of ions responsive mobile layout.

**Comment by jensstein** [comment]
i don't know if it would be a good idea to use a stock symbol to signify backups.
going with a single colour background or maybe a simple pattern sounds good.
it seems that the basic functionality of linear works without js so that's fine.

**Comment by lightonflux** [comment]
Sorry that i haven't done anything yet. But i was busy with other stuff. But the website is not forgotten.

Just found a nice layout on the web that has a nice "get involved" layout.

http://modoboa.org/

**Comment by DJaeger** [comment]
Is there something new?
I still hold an empty domain for nearly a year.

**Comment by lightonflux** [comment]
Thanks for the reminder and sorry for the delay.

Here some updates: 

In July i changed away from jekyll to html + css for simplicity. 

Today i started to implemented the get involved blocks similar to modoboa. There are some weird spacing issue i have to resolve. 

I  try to upload the first version before Christmas.

Then there are some things left to resolve:

 * english screen shots - mine are all in german
 * Polishing the texts
 * video/gif of mass backup (for the showcase section)

**Comment by DJaeger** [comment]
No problem.
Just wanted to hear an update.

Sounds nice.
You can temporarily change your language in system preferences under
System -> Sprache & Eingabe -> Sprache
to create the screenshots.

**Comment by jensstein** [comment]
brilliant - tell me if you need anything from me.

**Comment by lightonflux** [comment]
Sorry this never happened. I will close this issue. Anybody else who wants to continue is free to do so.
