### ISSUE TITLE
scheduling time wrong

### ISSUE THREAD

**Issue by lupa18** [jensstein/oandbackup#132]
I programned to run at 3 and it runs at 18

V 0.2.11

**Comment by jensstein** [comment]
do you mean that the schedule runs at 18 every time while being set at 3, or did it only happen once?

**Comment by lupa18** [comment]
I configured to run each 4 days at 3 am, and It runs each 4 days at 18. 
Screenshot: (in Spanish)
![screenshot_20160706-190603](https://cloud.githubusercontent.com/assets/463429/16665652/631bd546-4452-11e6-91f4-baffc7002c08.png)

**Comment by jensstein** [comment]
that is indeed strange. could you send me the file /data/data/dk.jens.backup/shared_prefs/schedules.xml and a logcat from when a schedule has run?

**Comment by nikwen** [comment]
Fixed in 0.2.13

**Comment by lupa18** [comment]
thanks!! I will test as soon as possible  :smile:
