### ISSUE TITLE
sheduled backup stucks in the process

### ISSUE THREAD

**Issue by sciamano** [jensstein/oandbackup#133]
I've created a sheduled backups of all my user apps (apk+data), every day at 3:00. I have about 70 user apps on my CM12 rom. Each time the backup starts in the night, it do not manage to finish and save all apps. Instead in he morning I see a notification like "backup APPNAME NN/70" where NN is a random number around 50..60. In the backup APPNAME folder there is a file three of app data instead of the zip file. However, when I start the same backup from the settings manually it does works as expected. Which options are available to find out there/why it stucks?

**Comment by jensstein** [comment]
do you have something like ```Killing 1963:dk.jens.backup/u0a40 (adj 15): empty #9``` in your logcat?
i think longer running schduled backups are getting killed because they are not started as a foreground service. when i have proper time i will try that.

**Comment by sciamano** [comment]
I have found this
```
[ 07-10 03:23:30.283  1022: 3758 I/ActivityManager ]
Killing 7627:dk.jens.backup/u0a64 (adj 13): excessive wake held 900135 during 900135
```
Is it possible to fix it by tuning (increasing) some system paratemer?

**Comment by ildar** [comment]
AFAIK app running gets very slow when a device is sleepy. It's probably
better to hold the wake lock during scheduled backups.
BTW current trends say to do such jobs when on ac power.

**Comment by jensstein** [comment]
could i get you to try if this one works: https://drive.google.com/file/d/0B0bNUNWd2wPPdGJlVGtTNjlwc0k/view?usp=sharing

@ildar yes, there has been another request for a check of power status before starting a scheduled backup. i think the default should be to run them on battery also though.
one workaround could be to re-acquire the wakelock after a number of backups.

**Comment by sciamano** [comment]
i've tested it last night and it woked, thanks!
just one thing, the backup was scheduled at 3:00, but the mtime of the created files spans from 3:32 to 3:54, looks like a 30 min delay somewhere

**Comment by jensstein** [comment]
brilliant :)
yes, i have seen that delay on my devices too. once in a while i have turned on one of my older devices and seen the schedule start then, maybe an hour later than its scheduled time. so i don't know if it can be that the system is sleeping to much to react to the alarm broadcast instantly.
