### ISSUE TITLE
Exclude APP 

### ISSUE THREAD

**Issue by mglinux** [jensstein/oandbackup#134]
Hi! 

Is it possible to exclude certain apps from backup? I have one APP that should not get backed up especially for scheduling.

**Comment by jensstein** [comment]
it's not possible right now, but it has been suggested before and i have also started looking at it. so at some point it will probably be possible.

**Comment by mglinux** [comment]
Good to hear. Had to disable whole copy symlinking because of termux APP. Else my whole internal storage gets copied, so disabling the APP would be great
