### ISSUE TITLE
I'm not able to recover my sms

### ISSUE THREAD

**Issue by Mannshoch** [jensstein/oandbackup#139]
If I try to recover I get a permission error. 

Root is available
Phone: Fairphone 2
Sourc: OS: Fairphone  OS 1.6.2
OS: Fairphone Open 16.08.0

**Comment by ildar** [comment]
You have to attach logcat.
Also make sure you restore on the same ROM you did the backup.

**Comment by Mannshoch** [comment]
Why should i do that on thevsame rom?

I changed from Fairphone OS 1.6.2 to Fairphone Open 16.08.0

Thats the point i had to use this app. because of the rom change my data partition was formated.
I wished to backup my sms.

**Comment by ildar** [comment]
SMS and call logs are stored in databases that are closely tied to the
Android version of the ROM. Hence its format may change.
I strongly suggest using apps that use SMS API for that. E.g. [SMS Backup+](
https://f-droid.org/repository/browse/?fdid=com.zegoggles.smssync)
In your particular case the problem may be different but it's impossible to
diagnose without logs.

**Comment by jensstein** [comment]
could you please post a logcat, the exact error you get and which package you were trying to restore.
i don't know what the difference between fairphone os 1.6.2 and fairphone open 16.08.0 entails but there really can't be a guaranties when restoring system applications on something else than the exact firmware it came from.

**Comment by treakiandroid** [comment]
i would suggest to use slight backup instead. app based backup is not that much good for system app based backups. i have only tested it for data based apps. On system level i am using complete backups using the recovery... see Slight backup (A very simple backup program) - https://f-droid.org/app/de.shandschuh.slightbackup

**Comment by Mannshoch** [comment]
As suggested by @ildar I used a third product to restore the sms. But the Problem with oandbackup exist also for a migration from Android 5 to Android 6 (Fairphone2)

**Comment by ildar** [comment]
Internal storage of Contacts/SMS/etc. can change between Android versions.
That's normal.
That's why using API to access them is much more reliable. This is how 3rd
party apps work.

**Comment by Mannshoch** [comment]
why do oandbackup don't work with them? Maybe it could do both backups together to let user or oandbackup chose the way back if the non api way not work.

Does a system upgrade also work with API?

**Comment by ildar** [comment]
I can't say about system upgrades. AFAIK many vendors demand Factory Reset
(aka Full Wipe) when upgrading to the different major version (like 5->6).
Anyway you'd better use SMS Backup+ then requesting @jensstein to implement
new functions already available in another app. Just my IMHO, of course.
