### ISSUE TITLE
Crash on startup after collecting package info. (java.lang.IllegalArgumentException: width must be > 0)

### ISSUE THREAD

**Issue by 5225225** [jensstein/oandbackup#140]
https://gist.github.com/5225225/a29bb2940305b80bf156be37283490e5 is a logcat of what looks like the important information. I could provide more detail if needed.

This happens with an empty oandbackup directory. If I downgrade to version 0.2.9, it works (In that I can view the list of packages without a crash, I haven't tested any more than that), but using 0.2.10 makes it fail like this (Even though I know I have used 0.2.10 successfully in the past)

I'm using CyanogenMod 13.0-20160820-SNAPSHOT-ZNH5YAO0J5-mako on a Nexus 4, which uses Android version 6.0.1.

**Comment by jensstein** [comment]
hmm, it says width must be > 0 even though it explicitly is set above zero on that line.
could you see if you still have the crash with this version: https://drive.google.com/file/d/0B0bNUNWd2wPPRDdTWVJQYnA0WFk/view?usp=sharing

**Comment by 5225225** [comment]
On Mon, Oct 17, 2016 at 12:24:40PM -0700, jensstein wrote:
> hmm, it says width must be > 0 even though it explicitly is set above zero on that line.
> could you see if you still have the crash with this version: https://drive.google.com/file/d/0B0bNUNWd2wPPRDdTWVJQYnA0WFk/view?usp=sharing 
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/jensstein/oandbackup/issues/140#issuecomment-254307103

No crash, it seems to work fine when backing up and restoring too.

**Comment by jensstein** [comment]
thanks for testing :)
