### ISSUE TITLE
backup fails on cm14.1

### ISSUE THREAD

**Issue by fajabird** [jensstein/oandbackup#146]
on cm14.1 (nougat) oandbackup does not work anymore and I can see the following two lines in logcat:

01-08 10:57:33.465 14466 14485 E oandbackup: customlist0: error while reading logfile: org.json.JSONException: Value java.io.FileNotFoundException of type java.lang.String cannot be converted to JSONObject
01-08 10:57:33.465 14466 14485 E oandbackup: oandbackup.log: error while reading logfile: org.json.JSONException: Value java.io.FileNotFoundException of type java.lang.String cannot be converted to JSONObject

Steps to reproduce:
Install cm14.1 and oandbackup
Setup toybox (/system/bin/toybox)
Try to backup something (does not matter what and if APP or DATA or both)
-> In my case backup starts and never ends (waited 30 minutes for a small app with no DATA) - no error message

**Comment by fajabird** [comment]
already tried with "setenforce 0" to no avail

**Comment by fajabird** [comment]
Could be a compatibility iissue with CM14.1 root daemon?

01-08 11:08:25.898 18068 18068 D su      : su invoked.
01-08 11:08:25.898 18068 18068 D su      : starting daemon client 10086 10086
01-08 11:08:25.900 18070 18070 D su      : remote pid: 18068
01-08 11:08:25.900 18070 18070 D su      : remote pts_slave: 
01-08 11:08:25.901 18070 18070 D su      : waiting for child exit
01-08 11:08:25.901 18072 18072 D su      : su invoked.
01-08 11:08:25.902 18072 18072 E su      : SU from: u0_a86
01-08 11:08:25.902 18072 18072 D su      : Checking whether app [uid:10086, pkgName: dk.jens.backup] is allowed to be root
01-08 11:08:25.909  1431  1588 I ActivityManager: Displayed dk.jens.backup/.OAndBackup: +85ms
01-08 11:08:25.912 18072 18072 D su      : Privilege elevation allowed by appops
01-08 11:08:25.912 18072 18072 D su      : Allowing via appops.
01-08 11:08:25.912 18072 18072 D su      : 10086 /system/bin/app_process32 executing 0 /system/bin/sh using binary /system/bin/sh : sh
01-08 11:08:25.912 18072 18072 D su      : Waiting for pid 18076.


and later on:

01-08 11:08:26.852 18070 18070 D su      : sending code
01-08 11:08:26.852 18070 18070 D su      : child exited
01-08 11:08:26.853 18068 18068 D su      : client exited 0
01-08 11:08:26.874 18098 18098 D su      : su invoked.
01-08 11:08:26.874 18098 18098 D su      : starting daemon client 10086 10086
01-08 11:08:26.880 18100 18100 D su      : remote pid: 18098
01-08 11:08:26.880 18100 18100 D su      : remote pts_slave: 
01-08 11:08:26.880 18100 18100 D su      : waiting for child exit
01-08 11:08:26.880 18102 18102 D su      : su invoked.
01-08 11:08:26.881 18102 18102 E su      : SU from: u0_a86
01-08 11:08:26.881 18102 18102 D su      : Checking whether app [uid:10086, pkgName: dk.jens.backup] is allowed to be root
01-08 11:08:26.883 18102 18102 D su      : Privilege elevation allowed by appops
01-08 11:08:26.883 18102 18102 D su      : Allowing via appops.
01-08 11:08:26.883 18102 18102 D su      : 10086 /system/bin/app_process32 executing 0 /system/bin/sh using binary /system/bin/sh : sh
01-08 11:08:26.883  2403  2403 I SuControllerImpl: Got change
01-08 11:08:26.883 18102 18102 D su      : Waiting for pid 18103.
01-08 11:08:26.908 18102 18102 D su      : Finishing su operation for app [uid:10086, pkgName: dk.jens.backup]
01-08 11:08:26.909  2403  2403 I SuControllerImpl: Got change
01-08 11:08:26.909 18102 18102 W IPCThreadState: Calling IPCThreadState::self() during shutdown is dangerous, expect a crash.
01-08 11:08:26.909 18102 18102 W IPCThreadState: Calling IPCThreadState::self() during shutdown is dangerous, expect a crash.
01-08 11:08:26.910 18100 18100 D su      : sending code
01-08 11:08:26.910 18100 18100 D su      : child exited
01-08 11:08:26.911 18098 18098 D su      : client exited 0

**Comment by Schroedingers-Cat** [comment]
I am on Linage OS (which is CM 14.1) and have the same problem. I updated from CM13 where oandbackup worked. However, I dont geht any log files written.

**Comment by alexbarcelo** [comment]
Maybe this is related to #141? I am not sure if the release that @jensstein was talking about has been done yet.

**Comment by takiainen** [comment]
Yeah, it think it is the same bug: try this https://drive.google.com/file/d/0B0bNUNWd2wPPTjJ3T25KaEVQd2c/view

He said earlier that he will publish this on F-Droid. Maybe he is busy with life?

**Comment by Schroedingers-Cat** [comment]
Yes, this build works. Thank you!

**Comment by takiainen** [comment]
No prob. It's a wonderful app, isn't it. Once you get used to using it is hard to live without.

**Comment by jensstein** [comment]
yes, unfortunately i don't have that much time at the moment.
but i did have time to make another release just now, so please see if the version which ends up on fdroid also have this issue fixed :)

**Comment by sniperle** [comment]
Working again for me with one exception, backing up "Android System" crashes the app.

01-20 21:00:37.468 I/oandbackup(27933): backup: Android System
01-20 21:00:37.492 E/AndroidRuntime(27933): 	at dk.jens.backup.OAndBackup$1.run(OAndBackup.java:152)
01-20 21:00:37.504 W/ActivityManager(1494):   Force finishing activity dk.jens.backup/.OAndBackup
01-20 21:00:38.076 E/WindowManager(27933): android.view.WindowLeaked: Activity dk.jens.backup.OAndBackup has leaked window DecorView@ef65c03[Android System] that was originally added here

**Comment by jensstein** [comment]
@sniperle thanks for reporting :) could i get you to open a separate issue and tell me if this works for you: https://drive.google.com/open?id=0B0bNUNWd2wPPTjJ3T25KaEVQd2c

**Comment by sniperle** [comment]
opened #147
