### ISSUE TITLE
Backing up "Android System" crashes with version 0.2.12

### ISSUE THREAD

**Issue by sniperle** [jensstein/oandbackup#147]
Backing up "Android System" crashes with version 0.2.12 (on LineageOS 14.1):

01-20 21:00:37.468 I/oandbackup(27933): backup: Android System
01-20 21:00:37.492 E/AndroidRuntime(27933): at dk.jens.backup.OAndBackup$1.run(OAndBackup.java:152)
01-20 21:00:37.504 W/ActivityManager(1494): Force finishing activity dk.jens.backup/.OAndBackup
01-20 21:00:38.076 E/WindowManager(27933): android.view.WindowLeaked: Activity dk.jens.backup.OAndBackup has leaked window DecorView@ef65c03[Android System] that was originally added here

**Comment by sniperle** [comment]
> @sniperle thanks for reporting :) could i get you to open a separate issue and tell me if this works for you: https://drive.google.com/open?id=0B0bNUNWd2wPPTjJ3T25KaEVQd2c

Fixed in this debug version, I think you can release it.

**Comment by sniperle** [comment]
Oh I've seen another error:

2017/01/22 - 11:21:07: cp: bad '/data/system/users/0/accounts.db': No such file or directory [Accounts]

**Comment by jensstein** [comment]
great :) i've just released 0.2.12.1 which should also fix the accounts.db issue.
