### ISSUE TITLE
error on backup of some apps

### ISSUE THREAD

**Issue by takiainen** [jensstein/oandbackup#155]
I get an error when trying to backup the data of Orfox. Sometimes the same error appears also when I try to backup the data of Firefox (but not always!?). However, if I choose "data+apk" the backup is always successful. This error doesn't appear on any other app (only Firefox and Orfox), and it persists across different roms. I'm using the latest F-Droid oandbackup version. See the log, and the screenshot.

02-05 15:36:08.464  1083 23101 I oandbackup: backup: Orfox
02-05 15:36:08.559  1083  1128 I HAL     : loaded HAL id=gralloc path=/system/lib/hw/gralloc.msm8974.so hmi=0x0 handle=0xafb88c50
02-05 15:36:08.712 23124 23124 D su      : remote req pid: 1083 
02-05 15:36:19.012  1083 23101 I oandbackup: return: 1 / error
02-05 15:36:19.148  1083  1128 I HAL     : loaded HAL id=gralloc path=/system/lib/hw/gralloc.msm8974.so hmi=0x0 handle=0xafb88c50
02-05 15:49:52.291  1083  1128 I HAL     : loaded HAL id=gralloc path=/system/lib/hw/gralloc.msm8974.so hmi=0x0 handle=0xafb88c50
02-05 15:49:52.301  1083  1128 I HAL     : loaded HAL id=gralloc path=/system/lib/hw/gralloc.msm8974.so hmi=0x0 handle=0xafb88c50
02-05 15:49:55.155  1083  1128 D OpenGLRenderer: endAllActiveAnimators on 0x8d5f0080 (RippleDrawable) with handle 0x9337a1e0
02-05 15:50:03.649  1083  1128 I HAL     : loaded HAL id=gralloc path=/system/lib/hw/gralloc.msm8974.so hmi=0x0 handle=0xafb88c50
02-05 15:50:06.258  1083  1128 I HAL     : loaded HAL id=gralloc path=/system/lib/hw/gralloc.msm8974.so hmi=0x0 handle=0xafb88c50
02-05 15:50:10.368  1083 30004 I oandbackup: backup: Orfox
02-05 15:50:10.467  1083  1128 I HAL     : loaded HAL id=gralloc path=/system/lib/hw/gralloc.msm8974.so hmi=0x0 handle=0xafb88c50
02-05 15:50:10.658 30042 30042 D su      : remote req pid: 1083 
02-05 15:50:19.310  1083 30004 I oandbackup: return: 1 / error
02-05 15:50:19.399  1083  1128 I HAL     : loaded HAL id=gralloc path=/system/lib/hw/gralloc.msm8974.so hmi=0x0 handle=0xafb88c50

![screenshot_20170205-153643](https://cloud.githubusercontent.com/assets/13743305/22626644/f4f27758-ebba-11e6-9f92-5d58a12a0727.png)

**Comment by jensstein** [comment]
this is because the lock file is a symlink pointing to a port on localhost (it seems) - the error should already be ignored for firefox though.
try this and see: https://drive.google.com/file/d/0B0bNUNWd2wPPTjJ3T25KaEVQd2c/view?usp=sharing

**Comment by takiainen** [comment]
Your new version works! First I tried to recreate the issue by backuping Firefox with the OLD version of oab, but it went through fine. Orfox failed though. After this I installed your fixed version, and both backuped ok.

**Comment by jensstein** [comment]
fantastic :)

**Comment by takiainen** [comment]
Do you mind pushing the fixed version into F-Droid?
