### ISSUE TITLE
Restore error: ": sed: No such file or directory"

### ISSUE THREAD

**Issue by Mannshoch** [jensstein/oandbackup#174]
I tryed to restor made Backup from Android 5.01 to Android 6 and got these error on every restore. Intersting detail around 70% of all apps where able to restore and work without Problem.

Installed XInternalSD  (deactivated the change of the path for internal data) and have full access to my sdcard.

![screenshot_20170623-193211](https://user-images.githubusercontent.com/7795891/28065858-ce562b1c-663a-11e7-8790-eaafb0b0c38b.png)

**Comment by ildar** [comment]
Would you try with XInternalSD or the whole Xposed switched off?
Also logcat and oandbakup.log could help.

**Comment by Mannshoch** [comment]
Maybe in the next two week, there is a reason to redo my Phone from plain again so I will try it.

**Comment by Mannshoch** [comment]
How should I upload a logcat.log? It seems there ist sensitive data in it.

**Comment by ildar** [comment]
Yes, mostly

**Comment by jensstein** [comment]
you can send the logcat to my email (j.stn.oab@gmail.com) - unless you use some very security-unaware apps your logcat shouldn't contain passwords but it might contain information such as your email or usernames. if you are not comfortable sharing the complete log you can try filtering it based on the pid or package name of oandbackup but this may filter out context needed to solve the issue.

**Comment by Mannshoch** [comment]
I did a factory reset and only installed SysLog for recording and Oandbackup. So no private data schould be inside this logs. I hope.
I tried to recover net.sourceforge.solitaire_cg (from f-droid) APK and data

[2017-07-25_13.20.zip](https://github.com/jensstein/oandbackup/files/1172991/2017-07-25_13.20.zip)

**Comment by ildar** [comment]
I see the relevant
> 07-25 13:19:03.755 E/oandbackup( 6246): no uid and gid found while trying
to set permissions

but don't know why it happens. Need to inspect source code... maybe later.

**Comment by Mannshoch** [comment]
Logcat and oandbackups.log from reseted Fairphone2 and fresh installed OS: 17.07.6

[oandbackup.txt](https://github.com/jensstein/oandbackup/files/1201285/oandbackup.txt)
[Log-2017-08-04-03.14.22.txt](https://github.com/jensstein/oandbackup/files/1201286/Log-2017-08-04-03.14.22.txt)

**Comment by Mannshoch** [comment]
problem solved.
It seems that busybox was missing.
I instslled it from f-droid and added " /system/xbin/busybox" to oandbackup

**Comment by ildar** [comment]
I think different. Probably you had it but it was incomplete: sed was
missing.
The app should check busybox AND its plugins. Need to check it.

**Comment by Mannshoch** [comment]
As far I know Android has it's own version of busybox called Toybox -> https://en.wikipedia.org/wiki/Toybox
