### ISSUE TITLE
could not get backups from k9mail/pep - oandbackup freeze

### ISSUE THREAD

**Issue by Mannshoch** [jensstein/oandbackup#178]
could not get backups from k-9/p≡p (k9mail with PGP support)

oandbackup seems freezing. The statusbar tells me at moment a time 15min ago.

App: https://f-droid.org/packages/pep.android.k9/
Phone: Fairphone 2
OS: FP open 17.06.4

**Comment by ildar** [comment]
oandbackup.log and logcat are mandatory, please provide.
P.S. we need to write it somewhere, tired to write the same again and again
🙂

**Comment by Mannshoch** [comment]
If I remove oandbackup.log and then do only a k9/pep backup oand do not create a log file.

[Logcat-2017-07-29-06.03.13.txt](https://github.com/jensstein/oandbackup/files/1185083/Log-2017-07-29-06.03.13.txt)

**Comment by ildar** [comment]
First line looks suspicious. Could you please reinstall and try again?

**Comment by Mannshoch** [comment]
I tested it again with:
actual pep from: https://fdroid.pep-security.net/
OS: FP open 17.07.6

I formated the Phone
Upgraded OS
Installed the actual k9Mail/pep
Set-up accounts 
did a backup. 

Now it worked. the only diferent I go. The title of this App not anymore contained an UTF8-character.

THE suspicious Line appeared again. See log. no oandbackup.log was created.
[Log-2017-08-04-02.15.00.txt](https://github.com/jensstein/oandbackup/files/1201278/Log-2017-08-04-02.15.00.txt)

**Comment by ildar** [comment]
Excuse me, it works but doesn't create oansbackup.log? 😲

**Comment by Mannshoch** [comment]
Yes.

**Comment by Mannshoch** [comment]
Could be closed. No problem anymore.
