### ISSUE TITLE
Just a question: backup and restore system settings

### ISSUE THREAD

**Issue by amo13** [jensstein/oandbackup#191]
Hey guys,
does anyone know if there is a possibility to back up system settings like activated "unknown sources", deactivated annoying touch sounds and maybe the quick settings tiles?
What do I need to select in order to back this up? (I'm on LineageOS 14.1)
I already tried restoring backups of:
```
com.android.providers.settings
com.android.settings
com.cyanogenmod.trebuchet
org.cyanogenmod.cmparts
```
I was also able to restore all my widgets with their respective positions, which is just amazing! But unfortunately, restoring system settings is what I am missing. 

I'd appreciate any idea! Thanks in advance!

**Comment by ildar** [comment]
Let me present my "idea"
Settings are very security sensitive and you generally don't want them to
be set/reset automatically.
For "Unknown sources" it's more safe to use F-Droid Privileged Extension
(Services to allow F-Droid to securely install and update apps) -
https://f-droid.org/app/org.fdroid.fdroid.privileged
Just IMHO

**Comment by amo13** [comment]
Thanks for your idea!
Yes, fdroid privileged is awesome, like fdroid in general! But it doesn't solve my problem just yet...
I actually do have a situation/scenario where I want to set some system settings automatically. Most of these are not relevant for security at all (like turning off sounds). The only security-relevant setting I want to set automatically is the "password visible" toggle, which is set to yes by default and makes your password semi-readable to anyone looking over your shoulder. 
To me, oandbackup looks like it should be able to do so, but it does not really or I'm not sure how to do it... 
Any idea?

**Comment by tulakalbeyo** [comment]
i want to be able to do this, too.. any clues? thanks!

**Comment by amo13** [comment]
this looks like a small issue with the new rust binary... maybe this can be fixed

**Comment by tulakalbeyo** [comment]
@jensstein sure thing, dude:

```
$ su
ether:/ #
ether:/ # ls -ld /data/user_de/0/org.lineageos.lineagesettings/
drwx------ 6 system system 4096 1971-12-12 04:46 /data/user_de/0/org.lineageos.lineagesettings/
ether:/ #
ether:/ # /data/data/dk.jens.backup/files/oab-utiens.backup/files/oab-utils owner /data/user_de/0/s owner /data/user_de/0/org.lineageos.lineagesettings/
{"uid": 1000, "gid": 1000}
ether:/ #
ether:/ # exit
$ 
```
