### ISSUE TITLE
Bug found in OandBackup. 

### ISSUE THREAD

**Issue by PeerzadaZeeshan** [jensstein/oandbackup#202]
#### Expected behavior

Tried to disable the application in OandBackup. It must be disabled after clicking on disable option. 

#### Actual behaviour

When I clicked on disable option it brings me to home screen. 

#### How to reproduce
Open the app. 

Long press on any app. 

Then there appears disable, uninstall, enable and share option. Press on disable option. 

It will bring you to home screen. 

* Browser: OandBackup
* Version:0.2.13
* Operating system:5.1.1

#### Recording Of The Bug
The Recording of the bug is in the GIF below. 
![20180320_120950.gif](https://res.cloudinary.com/hpiynhbhq/image/upload/v1521529156/z0r7zrixljpdalctxdvb.gif)

    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@peerzadazeeshan/bug-found-in-oandbackup">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by ildar** [comment]
Your video demonstrates you have an issue with getting root. If that's
right, it must be the root of your problem.

**Comment by 0xpr03** [comment]
@ildar please just close it if you think it's too minor. The reporting account is 24 days old and posts only kind of abuse related issues to android repos (10+), all of them related to utopian, from which I've some response.

**Comment by ildar** [comment]
@0xpr03 , I actually can't as I'm not an owner nor (formal) contributor.
Just a sentinel here )))

**Comment by jensstein** [comment]
@ildar is correct, i wouldn't see this as a bug.
