### ISSUE TITLE
changelog update

### ISSUE THREAD

**Issue by lupa18** [jensstein/oandbackup#204]
Hello, 
Changelog is not updated. Could you update it?

thanks !!

**Comment by strugee** [comment]
I also noticed this. Specifically, 0.2.12, 0.2.12.1, and 0.2.13 are missing.

**Comment by Matrixcoffee** [comment]
Indeed. I noticed 0.3.0 in F-Droid, but no changelogs.

Too late for TWIF now, but maybe next time.

**Comment by 894-572** [comment]
0.3.1 is out, no changelog.

**Comment by jensstein** [comment]
the changelog is updated now :)
https://github.com/jensstein/oandbackup/blob/master/changelog.md
