### ISSUE TITLE
Can't detect busybox

### ISSUE THREAD

**Issue by swan11jf** [jensstein/oandbackup#210]
On startup, error shows this: couldn't find busybox, please check error log 

error log shows this: sh: [1]: toybox: not found [busybox

Recently changed from Lineage (7.1.2) to AOSP Extended (8.1). It was working fine on Lineage

**Comment by ildar** [comment]
toybox or busybox required for oandbackup. Could you please check which of
the two you have?

**Comment by acuna-personal** [comment]
Busybox or Toybox are required, but Android have it from the box by default. Before Marshmallow (will be, I don't remember the version) it using Busybox, and after - Toybox. But OAB execute commands with Busybox and Toybox together, so at least one of them WILL working, so seems this message is only a warning, not error. Does OAB makes backups or not. In this situation it will on any case.

**Comment by acuna-personal** [comment]
@ildar please refers the OAB sources: https://github.com/jensstein/oandbackup/blob/master/src/dk/jens/backup/ShellCommands.java line 369:

> android 6 has moved to toybox which doesn't include [ or [[

**Comment by ildar** [comment]
Right. I am wrong. Toybox came into AOSP in 2014.

**Comment by acuna-personal** [comment]
Don't worry about it ;) We all mistaken.

**Comment by swan11jf** [comment]
Is there anyway of transferring backups manually then?

**Comment by acuna-personal** [comment]
Where do you want to tranfser it? You could made it, but can't apply it after?

**Comment by swan11jf** [comment]
The backup was made on Android 7. I changed to a new ROM, so had to wipe my device. I've upgraded to android 8 now, so as oandbackup doesn't seem to be working for me, i want to restore this backup to the same device

**Comment by acuna-personal** [comment]
I'm so sorry for forgot to answer you. If you have backups, you can restore it manually. You need a filemanager which can set chmods (like Solid Explorer, it's really cool), put your backups folder to `/data/data` folder (e. g. `/data/data/your.app.name`) and set 777 chmods to all of it.

**Comment by jensstein** [comment]
it seems like your device doesn't have toybox or have a non-standard installation of some *box. could you please see if running ```toybox``` in a terminal emulator on your device or via ```adb shell``` gives a result (it should list the included commands).
and could you post the output of running ```ls -l /system/bin/```

also, remember checking if you have a value set for busybox under "custom paths" in the preferences. if it's set, the old value may not be valid for your new system.

(by the way, i'm in the process of making a replacement for {toy,busy}box, which will ship with oab)

**Comment by swan11jf** [comment]
Ok, here's the link to the output

https://file.io/KVniGn

**Comment by jensstein** [comment]
great :) your link gives me 404 but i'm glad you got it to work

**Comment by simongcc** [comment]
I am using a legacy Samsung tablet with Android 4.1.2, it mentions this error when backup data and apk. Is it possible to add those tools in 4.1.2?

**Comment by ildar** [comment]
1. find out if you have busybox or toybox
2. if not, get a Busybox Installer. F-Droid Archive should have one for
your vintage system
!!! surely root required.
