### ISSUE TITLE
Couldn't find oab-utils

### ISSUE THREAD

**Issue by simonsen23** [jensstein/oandbackup#212]
When I start oandbackup I get the following error:
> couldn't find oab-utils - running in legacy mode, please report this to the developer

Here is the corresponding logfile:
[log_oabutils.txt](https://github.com/jensstein/oandbackup/files/2127089/log_oabutils.txt)

When I look for the _permissions_ from oab-utils I get the following result:
`ls -l oab-utils`:
> -rwxrw---- (...)
> oab-utils

I have a Oneplus 2 with ARM64 and Lineage OS 15.1

**Comment by jensstein** [comment]
okay, could you try this apk and send me the logs (both logcat and oandbackup.log):
https://gitlab.com/jensstein/oandbackup/builds/artifacts/oabutils-issue-212/raw/apks/arm64/oandbackup-debug.apk?job=build
(we expect it to give the same result - just with some more logging)

also, try running ```/data/data/dk.jens.backup/files/oab-utils -h``` as the root user on your device.

and if others want to help debugging, there are apks for the other architectures here: 
https://gitlab.com/jensstein/oandbackup/builds/artifacts/oabutils-issue-212/browse/apks?job=build

**Comment by simonsen23** [comment]
Here are my logfiles with the changed apk:

[oandbackup.log](https://github.com/jensstein/oandbackup/files/2129974/oandbackup.log)

[logcat_oab.txt](https://github.com/jensstein/oandbackup/files/2129976/logcat_oab.txt)

I could not run the command `oab-utils -h` and I get the following error:

> sush: oab-utils: not found

**Comment by jensstein** [comment]
super, please try this:
https://gitlab.com/jensstein/oandbackup/-/jobs/76944268/artifacts/file/apks/arm64/oandbackup-debug.apk
i expect it to work now.
your error on running the command manually seems to be because you didn't run it with an absolute path (```/data/data/dk.jens.backup....```), so i think it should work if you do that.

**Comment by simonsen23** [comment]
Now I don't get the oab-utils error anymore.

**Comment by jensstein** [comment]
great :)

**Comment by mase76** [comment]
I have the same issue with the F-Droid package.

**Comment by JonnyTech** [comment]
Same here with oandbackup  0.3.2-x86.apk from fdroid. Permissions when installed are 660. Changing to 775 shows error attached:

![img_20181027_120331](https://user-images.githubusercontent.com/3584732/47603199-932e8000-d9e0-11e8-99ad-d8df91a5a7da.jpg)

Also have to reset each time.

**Comment by MarcAnt01** [comment]
@jensstein I've been experiencing the same issue after upgrading to 0.3.2, everything was working here, I have tried the same procedure as @simonsen23 , but the apk doesn't install 
OnePlus 3 OmniDragon Android 8.1

**Comment by MarcAnt01** [comment]
Will let you know as soon as new version is out

**Comment by JonnyTech** [comment]
> are you all on arm64 devices?

Yes, thanks for replying

**Comment by bipox** [comment]
I have this issue in 0.3.3

**Comment by lotth** [comment]
Same for me with yesterday's version 0.3.3 x86_64 from f-droid.

**Comment by JonnyTech** [comment]
@lotth are you sure that you are using a `x86_64` device? F-droid is detecting it wrong. You may want to force install the `arm64` version.

**Comment by lotth** [comment]
I have an arm64 phone, and I assumed there was a mistake in d-droid naming scheme. I reverted to 0.3.2-arm64 and the normal behaviour is back.
Thanks for pointing out the issue, I shall be more careful about f-droid detection.

**Comment by JonnyTech** [comment]
@lotth version 0.3.3-arm64 (2303) works too, download with the f-droid client (select manually from list) or direct from https://f-droid.org/repo/dk.jens.backup_2303.apk

**Comment by jomo** [comment]
Can confirm uninstalling and re-installing `0.3.3-arm64` in F-Droid worked!
Be careful doing this though, it also deletes the oandbackup directory on the sdcard (which contained all my backups ¯\\\_(ツ)\_/¯)

**Comment by JonnyTech** [comment]
There is no need to uninstall. As you are already rooted in order to use oandbackup, just replace the apk in /data/app/ with the correct one.

**Comment by gitgt** [comment]
Same as Issue 222

**Comment by gitgt** [comment]
Please close this issue  if resolved.

**Comment by LinuxOnTheDesktop** [comment]
I don't this issue is resolved, in that people - including me - are still encountering it when they use f-droid to get the app.
