### ISSUE TITLE
Restore fails (Android 9.0)

### ISSUE THREAD

**Issue by ghost** [jensstein/oandbackup#217]
I updated my OnePlus 6 to Android 9.0 (official release) and since then oandbackup fails to restore any of my backed-up apps. 

My phone is rooted (Magisk 17.1) and I have BusyBox installed. I'm not sure what the issue is, but I attached a copy of the error log.

[error_log.txt](https://github.com/jensstein/oandbackup/files/2409655/error_log.txt)

**Comment by nonno-cicala** [comment]
I worked around this. The problem is it cannot install the apk from the path where oandbackup stores it, so when I needed to install an apk from the backup I copied it (base.apk inside the package backup dir) in /data/local/tmp/ , as suggested by the error log, and installed it with `pm install /data/local/tmp/base.apk` (IIRC, I did that some time ago).

**Comment by mahesh1729** [comment]
I think issue is with Android 9. This link explains a bit https://stackoverflow.com/questions/50540334/install-apk-using-root-handling-new-limitations-of-data-local-tmp-folder

**Comment by jensstein** [comment]
it seems to be changes in selinux rules preventing system_server from accessing the storage directories. can you try this apk: https://gitlab.com/jensstein/oandbackup/-/jobs/125046812/artifacts/file/apks/oandbackup-universal-debug.apk
(or another debug apk appropriate for your device here: https://gitlab.com/jensstein/oandbackup/-/jobs/125046812/artifacts/browse/apks/)

**Comment by andretiagogr** [comment]
> it seems to be changes in selinux rules preventing system_server from accessing the storage directories. can you try this apk: https://gitlab.com/jensstein/oandbackup/-/jobs/125046812/artifacts/file/apks/oandbackup-universal-debug.apk

It works. I tried that apk on android 9 and I was able to restore an app without any error

**Comment by jensstein** [comment]
brilliant :)

**Comment by 07416** [comment]
Is this still an issue with the latest 0.3.5 version? Updated to Android 9, installed Busybox and the backup process fails.

**Comment by 07416** [comment]
> 
> 
> it seems to be changes in selinux rules preventing system_server from accessing the storage directories. can you try this apk: https://gitlab.com/jensstein/oandbackup/-/jobs/125046812/artifacts/file/apks/oandbackup-universal-debug.apk

This version works. I hope that the stable build will be updated with Android 9 compatibility.

**Comment by sentriz** [comment]
working for me now too 😎

**Comment by Eternal010** [comment]
Debug apk working for android 10.... 💯

**Comment by ghost** [comment]
https://github.com/machiav3lli/oandbackupx
