### ISSUE TITLE
Backups complete w/oab-utils errors

### ISSUE THREAD

**Issue by wilmarcdw** [jensstein/oandbackup#227]
Just updated to 0.3.4 via F-Droid. After a backup completes I get errors on the screen. Warnings actually. Backed up data seems fine.

AOSPA-L / Paranoid Android Lollipop.
microG.
SuperSU 2.82.

2018/11/23 - 03:08:09: WARNING: linker: /data/data/dk.jens.backup/files/oab-utils: unused DT entry: type 0x6fffffff arg 0x3 [oab-utils]

2018/11/23 - 03:08:09: WARNING: linker: /data/data/dk.jens.backup/files/oab-utils: unused DT entry: type 0x6ffffffe arg 0x1640 [oab-utils]

2018/11/23 - 03:07:51: WARNING: linker: /data/data/dk.jens.backup/files/oab-utils: unused DT entry: type 0x6fffffff arg 0x3 [oab-utils]

2018/11/23 - 03:07:51: WARNING: linker: /data/data/dk.jens.backup/files/oab-utils: unused DT entry: type 0x6ffffffe arg 0x1640 [oab-utils]

2018/11/23 - 03:07:51: WARNING: linker: /data/data/dk.jens.backup/files/oab-utils: unused DT entry: type 0x6fffffff arg 0x3 [oab-utils]

**Comment by jensstein** [comment]
thanks for reporting! these warnings should be harmless for now. but i'll try fixing it as soon as i can :)
