### ISSUE TITLE
Chinese (Taiwan) translation request on Transifex

### ISSUE THREAD

**Issue by cges30901** [jensstein/oandbackup#241]
I requested Chinese (Taiwan) translation on Transifex, but it hasn't been accepted, so I can not translate. Can you add Chinese (Taiwan) on Transifex?

**Comment by jensstein** [comment]
added! sorry for not being so active on transifex.

**Comment by cges30901** [comment]
Thank you! Now I have requested to join Chinese (Taiwan) team.
