### ISSUE TITLE
no documentation how to set up encryption

### ISSUE THREAD

**Issue by TjrGithub** [jensstein/oandbackup#246]
There is an entry in the preferences, "encryption". But there is no documentation how to get it working, neither in-app nor on the website nor in the FDroid store description.

So far, the only hint I have found is https://github.com/jensstein/oandbackup/issues/101. It says to install org.sufficientlysecure.keychain. If that is the correct approach, I would expect a pointer on the website and in-app and FDroid.

Once encryption works conveniently and reliably, it would also solve #244.

Edit: installing openkeychain does indeed activate the preferences item.

Versions:
* lineageos-with-microg 15.1 as of 2019-04-10 with addon_root on a Mido
* xposed 90-beta3 and xprivacylua 1.24 FDroid, don't restrict oandbackup
* oandbackup 0.3.5-universal Fdroid
* openkeychain 5.2 Fdroid

**Comment by jensstein** [comment]
I've added a section on cryptography to the readme: 
https://github.com/jensstein/oandbackup/blob/cryptography-touchup/README.md
If you have any suggestions I'd be glad to hear them :)

**Comment by TjrGithub** [comment]
Thanks, that's great already.
