### ISSUE TITLE
OAB do not restore data of the app is being restored

### ISSUE THREAD

**Issue by vadiof** [jensstein/oandbackup#251]
Lately I my phone's system was broken and I was forced to fully wipe my phone. Tried to restore my apps early backed up by OAB after system reinstallation and found that app's data does not restore at all. I stare at logcat and see that OAB don't find files contained in zip-archive it saved alongside of apk

**Comment by vadiof** [comment]
Luckily I gazed a little more and found that storage that contains backups is full and has no free space for unzipping data of the apps

**Comment by haja** [comment]
so, it was not the apps fault then? because I'm now wondering if I should trust the backups of this app...
@vadiof if the issue is solved, do you might want to close it?
