### ISSUE TITLE
Allow encryption of backups

### ISSUE THREAD

**Issue by manwesulimo2004** [jensstein/oandbackup#66]
I have my phone's internal storage encrypted but not my SD card. I would love to be able to make backups on a regular basis and store them on the SD card. But obviously storing them there without encryption would defeat the point.

I propose an option in oandbackup for encrypting backups. I think it would make sense to tie this feature to a second feature I will suggest in another issue (#67): The ability to store all backups in one single archive. Since encrypting only the individual files would reduce security significantly.

**Comment by mase76** [comment]
I think, you could use openkeychain as a helper program.
GPG encryption would be great!
Encryption is really necessary, as the backups may contain
sensible data.

**Comment by jensstein** [comment]
@mase76 actually, encryption has been implemented. the recent 0.2.10 release contains it. i have used the openpgp api library written by the openkeychain developer. so encryption should be possible if a program which implements that library is installed. at the moment this may be limited openkeychain and apg but i'm not sure.
so please test and report issues. presently it may be encrypting too slowly to work properly on very big packages.

**Comment by mase76** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

Hey!
Great! I will test when it is available in rhe f-droid repo.


Am 29. Januar 2015 22:05:24 MEZ, schrieb jensstein <notifications@github.com>:
>@mase76 actually, encryption has been implemented. the recent 0.2.10
>release contains it. i have used the openpgp api library written by the
>openkeychain developer. so encryption should be possible if a program
>which implements that library is installed. at the moment this may be
>limited openkeychain and apg but i'm not sure.
>so please test and report issues. presently it may be encrypting too
>slowly to work properly on very big packages.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/jensstein/oandbackup/issues/66#issuecomment-72103824

- --
gpg: 383107c4
https://www.setho.org/people
-----BEGIN PGP SIGNATURE-----

iQI7BAEBCAAlHhxUaG9tYXMgTWFhw58gPG1hc2VAc2V0aG8ub3JnPgUCVMsviwAK
CRBoEivDODEHxBzDD/0ad0y4u7N7V52e3GknNHXUNNgmgIB7ZWoi21N9MFJhD/fa
2xgREaeL3vE9NlKEvvYNenlclQc//TV6H/b/gXcE3ZBCx5Q1PJEMoaFs7jO8FChK
bSyaOpKwMHpNehHCQl8HT2jzYxvd79n8Gbkdlc8IMEt8CXrFu1/7OrqA+WsNUfm2
YhUEfSMc7CURs1cEvPBfebclWqjdfzK4+tOUBH0e/NQK730ouse6X/fnZddn540o
71qW/bNU5BDq6l0yJp3/5ekCQQp32FrIdC9hRdvTi0VEIuSORz122kUl34qxEJ5Y
/eO6BH0Ck60iEazKP2I9XywjcAxQVsu3xmKS72IWY1OidydJbFhebzj0se9670Z8
JrpXgnxEeU/r+h/c+/dra4Bjvsd++IACNjNe1iVqjl3YfmgCh1LITMiv/v4z79XG
CzEKFkuCnsUyF5OPDYATzFuA0cfG8HZamDNXrbwN2y1W9yT8MokEwSGlbEUIqS/r
f8XHrIdjJgNSl/1FYxkoa9dAbjn217i7Jm7o+6CD/2wU/pRflh64Pxc2eMn50x+H
8a6D68X7VDz3fU2VnddK6tKKkw1kQvN8T8+gNIoDZ+gITnSdhPN1wFQiR6gmsXSk
ythG5atH1ftC4mQ3k7DG8YU4jCD4HSwrzoFfXurVDSBsD+5mqwoGL04GdiZ1qQ==
=wkv5
-----END PGP SIGNATURE-----

**Comment by DJaeger** [comment]
I'm using this for months without trouble.
I think you can close this issue.

**Comment by jensstein** [comment]
great, that's nice to hear :)
