### ISSUE TITLE
No obvious way to get the version number of oab

### ISSUE THREAD

**Issue by lightonflux** [jensstein/oandbackup#78]
I tried to find the version number but i couldn't find an about entry or a version number in the help.

Sure i can backup oab to see which version i am using, but … it's not optimal.

A simple version string in the help would help. :)

**Comment by jensstein** [comment]
yes, this is a good idea :) i'll do once i'm done working on restoring compiled library files.

**Comment by jensstein** [comment]
implemented with commit 82b6a9c. i just put it at the top in the help screen.
