### ISSUE TITLE
Force close on Android Lollipop

### ISSUE THREAD

**Issue by sniperle** [jensstein/oandbackup#79]
Force close on Android Lollipop

01-06 16:43:50.092 I/ActivityManager(2418): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=dk.jens.backup/.OAndBackup (has extras)} from uid 10009 on display 0
01-06 16:43:50.182 I/ActivityManager(2418): Start proc dk.jens.backup for activity dk.jens.backup/.OAndBackup: pid=9814 uid=10257 gids={50257, 9997, 1028, 1015} abi=armeabi-v7a
01-06 16:43:50.652 I/ActivityManager(2418): Displayed dk.jens.backup/.OAndBackup: +497ms
01-06 16:43:50.742 I/Timeline(2418): Timeline: Activity_windows_visible id: ActivityRecord{2f71bbb7 u0 dk.jens.backup/.OAndBackup t141} time:7530932
01-06 16:43:52.802 E/AndroidRuntime(9814): 	at dk.jens.backup.OAndBackup$1.run(OAndBackup.java:105)
01-06 16:43:52.802 W/ActivityManager(2418):   Force finishing activity dk.jens.backup/.OAndBackup
01-06 16:43:53.272 E/WindowManager(9814): android.view.WindowLeaked: Activity dk.jens.backup.OAndBackup has leaked window com.android.internal.policy.impl.PhoneWindow$DecorView{14822143 V.E..... R......D 0,0-1026,348} that was originally added here

**Comment by jensstein** [comment]
i think you have snipped some of the stacktrace away from the log but it seems to be this bug: https://github.com/jensstein/oandbackup/issues/73
there is a link to an apk in the last comment on that bug. can you confirm whether this is a duplicate and whether the apk fixes the bug?
if this is a separate issue, could you please describe how to reproduce it and attach a little more log info.
thanks :)

**Comment by sniperle** [comment]
Didn't cut out anything. The error happens directly after starting the app. Your development version is working well. Thank you.  :-)
