### ISSUE TITLE
App icons incredibly small in high DPIs

### ISSUE THREAD

**Issue by mvdan** [jensstein/oandbackup#80]
I assume this is an issue on high dpi devices only, possibly because you use icons of a certain size (maybe mdpi, 48x48 pixels?) which are tiny on larger resolutions.

Screenshot attached:
![](https://i.imgur.com/rxyamcg.png)

**Comment by jensstein** [comment]
they were hardcoded at 32x32. with commit 17cff9a 32 is now multiplied with the screen density. this seems to work fine in the emulator but i don't have any real-world high-density devices to test it on.
maybe the base value (32) should be customizable too.
