### ISSUE TITLE
FR: Encrypted backups

### ISSUE THREAD

**Issue by gerroon** [jensstein/oandbackup#85]
Hi

I use external sd card for my oan backups but there are hardly any roms that support encrypting the external cards. It would be great if OB supports encrypting the backups.

thanks

**Comment by jensstein** [comment]
hi, encryption is already implemented: https://github.com/jensstein/oandbackup/issues/66
you just need an openpgp provider (e.g. openkeychain). then you can enable encryption under preferences -> cryptography.
please test it out and report bugs :)

**Comment by gerroon** [comment]
Thanks. Can it ecnrypt existing backup? 

thanks for this great app. It makes life easier

**Comment by jensstein** [comment]
no, it can't encrypt existing backups. but it's something i might implement in a future version.
you could encrypt them manually with a separate openpgp program and give the encrypted file a ".gpg" extension (so "/sdcard/oandbackups/com.example.app/com.example.app.zip" becomes "/sdcard/oandbackups/com.example.app/com.example.app.zip.gpg"). please test if it works before relying on it though.

you're welcome :)
